### ISSUE TITLE
Request: restartless feature

### ISSUE THREAD

**Issue by Tallefer** [nohamelin/xseei#3]
Thank you for making this useful addon!
Please, make it restartless so it could be used "on the go" the same minute any user sees it for the first time, instead of restarting the whole mountain of tabs and everything else.

**Comment by nohamelin** [comment]
Hi,
That will not happen, as it's not possible to write an add-on as it as a (restartless) WebExtensions add-on, and there isn't point in rewriting it as a restartless legacy add-on that will be impossible to install in Fx 57 and later versions.

The alternative Scratchpad tools that I wrote for Fx57 don't require a browser restart, check:
http://forums.mozillazine.org/viewtopic.php?p=14771666#p14771666

...and later posts.

**Comment by Tallefer** [comment]
There is a point, because ESR 52 is still used (and will be, for at least half a year more) by many people.
But thanks for providing a Scratchpad-based workaround as well. It is far from being comfortable to use, but at least it's working.

**Comment by nohamelin** [comment]
Yeah, ESR 52 can still be considered supported (I use it as main browser): new releases with bug corrections or the additions of new translations could still happen, but I will not write new features for it.
