### ISSUE TITLE
JS exception when executing xseei.export-all.js

### ISSUE THREAD

**Issue by c0d1ng** [nohamelin/xseei#4]
When trying to execute the `xseei.export-all.js` script, I get the following error message:
```
Exception: TypeError: Cu is undefined
@Scratchpad/2:73:1
@Scratchpad/2:68:2
```

**Comment by nohamelin** [comment]
Hi,
Please verify that the **devtools.chrome.enabled** preference is true in about:config, as it's mentioned in the description of the file.

If that doesn't solve anything, please tell me at least your OS and Fx version.

**Comment by nohamelin** [comment]
I got another report about it in the comments of the gist page.

I will investigate it.

**Comment by c0d1ng** [comment]
Ah, I totally read over that part. Maybe put that as step 1, for those lazy guys like me ;)
Now it's working, thanks for your help!

**Comment by nohamelin** [comment]
I followed your suggestion: the instructions to run it were updated.
